"""not null 추가 

Revision ID: 235ff38bff85
Revises: 4ef9c8fd0bb7
Create Date: 2017-06-27 23:17:20.712627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '235ff38bff85'
down_revision = '4ef9c8fd0bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.alter_column('accounts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('accounts', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('accounts', 'name',
               existing_type=mysql.VARCHAR(length=12),
               nullable=False)
    op.alter_column('accounts', 'nickname',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('accounts', 'passwd',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'passwd',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('accounts', 'nickname',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('accounts', 'name',
               existing_type=mysql.VARCHAR(length=12),
               nullable=True)
    op.alter_column('accounts', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('accounts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('passwd', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
