"""empty message

Revision ID: 31baefc049be
Revises: ea7aa7668b22
Create Date: 2017-06-23 21:53:53.924486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31baefc049be'
down_revision = 'ea7aa7668b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('title', mysql.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
