"""날짜 컬럼명 수정정

Revision ID: 3bd57d4d1ecf
Revises: c29923c33dc2
Create Date: 2017-06-27 15:14:55.979644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bd57d4d1ecf'
down_revision = 'c29923c33dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('accounts', 'crated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('crated_at', mysql.DATETIME(), nullable=False))
    op.drop_column('accounts', 'created_at')
    # ### end Alembic commands ###
