"""empty message

Revision ID: 419ddb3f4752
Revises: 696318e208a7
Create Date: 2017-07-01 16:27:45.868830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '419ddb3f4752'
down_revision = '696318e208a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'device_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('device_id', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
