"""empty message

Revision ID: 6f2d7dcd8ef9
Revises: 266ce1233584
Create Date: 2017-06-22 14:10:34.830783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2d7dcd8ef9'
down_revision = '266ce1233584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('flag', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'flag')
    # ### end Alembic commands ###
