"""empty message

Revision ID: a6fb627dca55
Revises: 0b52df29be48
Create Date: 2017-06-22 22:51:54.418631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fb627dca55'
down_revision = '0b52df29be48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwd', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passwd')
    # ### end Alembic commands ###
