"""empty message

Revision ID: c29923c33dc2
Revises: d47a8cf78053
Create Date: 2017-06-26 18:02:40.455620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29923c33dc2'
down_revision = 'd47a8cf78053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('passwd', table_name='accounts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('passwd', 'accounts', ['passwd'], unique=True)
    # ### end Alembic commands ###
