"""empty message

Revision ID: cebbef4a4c6a
Revises: e8e3c5ef54db
Create Date: 2017-07-10 18:42:47.103513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cebbef4a4c6a'
down_revision = 'e8e3c5ef54db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'passwd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('passwd', mysql.VARCHAR(length=64), nullable=False))
    # ### end Alembic commands ###
