"""empty message

Revision ID: d054fd8553a2
Revises: d159a957cb7a
Create Date: 2017-07-01 16:30:06.376280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd054fd8553a2'
down_revision = 'd159a957cb7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=460), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=60), nullable=False),
    sa.Column('passwd', sa.String(length=93), nullable=False),
    sa.Column('profile_img', sa.String(length=255), nullable=True),
    sa.Column('voice', sa.String(length=120), nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.Column('evnt_point', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
