"""empty message

Revision ID: d47a8cf78053
Revises: 31baefc049be
Create Date: 2017-06-26 17:54:46.252928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47a8cf78053'
down_revision = '31baefc049be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('passwd', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=200), nullable=True),
    sa.Column('crated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('passwd')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
