"""empty message

Revision ID: e8e3c5ef54db
Revises: 
Create Date: 2017-07-10 18:27:17.131975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e3c5ef54db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('passwd', sa.String(length=64), nullable=False),
    sa.Column('profile_img', sa.String(length=255), nullable=True),
    sa.Column('voice', sa.String(length=120), nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.Column('evnt_point', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
