"""empty message

Revision ID: ff232f426abf
Revises: cebbef4a4c6a
Create Date: 2017-07-10 18:43:09.068785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff232f426abf'
down_revision = 'cebbef4a4c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('passwd', sa.String(length=98), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'passwd')
    # ### end Alembic commands ###
